(()=>{
const CORE=window.LearningDB;if(!CORE)return;
const EXT_KEY='learningOS_cognitive_v4',EXT_SCHEMA='cognitive-extension/1.0';
const uid=(p='cx')=>p+'_'+(crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random().toString(36).slice(2));
const now=()=>new Date().toISOString();
const empty=()=>({schema:EXT_SCHEMA,createdAt:now(),updatedAt:now(),snapshots:[],annotations:[],hypotheses:[],modelVersions:[{id:'model_1',createdAt:now(),name:'Cognitive Underground v4',rulesVersion:'1.0'}],dismissedHypotheses:[]});
let state;try{state=JSON.parse(localStorage.getItem(EXT_KEY)||'null')||empty()}catch(e){state=empty()}
function save(){state.updatedAt=now();localStorage.setItem(EXT_KEY,JSON.stringify(state))}
function active(){try{return JSON.parse(localStorage.getItem(CORE.ACTIVE_KEY)||'null')}catch(e){return null}}
function appendSnapshot(x){const item={id:uid('snap'),timestamp:now(),sessionId:x.sessionId||null,nodeId:x.nodeId||null,current:x.current||'',holding:x.holding||'',openQuestion:x.openQuestion||'',nextReturn:x.nextReturn||'',friction:Array.isArray(x.friction)?x.friction:[],source:'user',schemaVersion:1};state.snapshots.push(item);save();CORE.addRecord('workspace_snapshot',{nodeId:item.nodeId,sessionId:item.sessionId,content:item.current,metadata:{snapshotId:item.id,holding:item.holding,question:item.openQuestion,next:item.nextReturn,friction:item.friction,engineVersion:'cognitive-v4'}});return item}
function annotate(recordId,kind,text='',metadata={}){const a={id:uid('ann'),timestamp:now(),recordId,kind,text,metadata,schemaVersion:1};state.annotations.push(a);save();return a}
function recordsForNode(nodeId){return CORE.db.records.filter(r=>r.nodeId===nodeId).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp))}
function deriveTransitions(){const out=[];for(const s of Object.values(CORE.db.sessions)){const rs=CORE.db.records.filter(r=>r.sessionId===s.id).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp));for(let i=0;i<rs.length;i++){if(!['question','revisit'].includes(rs[i].type))continue;const later=rs.slice(i+1).find(r=>['distinction','gotit'].includes(r.type));if(later)out.push({kind:'transition',nodeId:s.nodeId,fromRecordId:rs[i].id,toRecordId:later.id,from:rs[i].type,to:later.type,seconds:Math.max(0,(new Date(later.timestamp)-new Date(rs[i].timestamp))/1000),sessionId:s.id})}}return out}
function deriveIncubations(){const out=[];for(const nid of Object.keys(CORE.db.nodes)){const rs=recordsForNode(nid);for(let i=0;i<rs.length;i++){if(!['question','revisit'].includes(rs[i].type))continue;const later=rs.slice(i+1).find(r=>['gotit','distinction'].includes(r.type)&&new Date(r.timestamp)-new Date(rs[i].timestamp)>=6*3600*1000);if(later)out.push({kind:'incubation_candidate',nodeId:nid,fromRecordId:rs[i].id,toRecordId:later.id,hours:(new Date(later.timestamp)-new Date(rs[i].timestamp))/3600000})}}return out}
function deriveFriction(){const by={};CORE.db.records.filter(r=>r.type==='question').forEach(r=>{by[r.nodeId]=(by[r.nodeId]||0)+1});return Object.entries(by).filter(([,n])=>n>=2).map(([nodeId,n])=>({kind:'friction_candidate',nodeId,questionCount:n,note:'Repeated questions observed. Cause is unknown; do not infer ability or diagnosis.'}))}
function refreshHypotheses(){const derived=[...deriveTransitions(),...deriveIncubations(),...deriveFriction()],keyOf=h=>[h.kind,h.nodeId,h.fromRecordId||'',h.toRecordId||''].join('|'),existing=new Set(state.hypotheses.map(keyOf));derived.forEach(h=>{if(!existing.has(keyOf(h)))state.hypotheses.push({id:uid('hyp'),createdAt:now(),modelVersion:'model_1',status:'candidate',confidence:'low',...h})});save();return state.hypotheses}
function bundle(){return {bundleType:'learning-os-portable-bundle',bundleVersion:1,exportedAt:now(),core:CORE.db,extensions:{cognitiveV4:state}}}
function downloadBundle(){const blob=new Blob([JSON.stringify(bundle(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`learning-os-full-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function mergeExtension(x){if(!x)return;for(const k of ['snapshots','annotations','hypotheses','modelVersions']){const ids=new Set((state[k]||[]).map(v=>v.id));(x[k]||[]).forEach(v=>{if(v&&v.id&&!ids.has(v.id))state[k].push(v)})}save()}
async function importBundle(file){const text=await file.text(),x=JSON.parse(text);if(x?.bundleType==='learning-os-portable-bundle'){if(x.core)CORE.merge(x.core);mergeExtension(x.extensions?.cognitiveV4);return true}CORE.merge(x);return true}
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const path=nid=>esc(CORE.pathOf(nid).join(' › '));
function hideAll(){document.querySelectorAll('.app>section').forEach(s=>s.classList.add('hidden'))}
function showUnderground(){refreshHypotheses();hideAll();document.getElementById('underground').classList.remove('hidden');renderUnderground()}
function closeUnderground(){document.getElementById('underground').classList.add('hidden');document.getElementById('home').classList.remove('hidden')}
function renderUnderground(){const t=deriveTransitions(),inc=deriveIncubations(),fr=deriveFriction(),box=document.getElementById('undergroundBody'),latest=state.snapshots.slice().sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)).slice(0,5);box.innerHTML=`<div class="card"><div class="recordType">MENTAL WORKSPACE</div><div class="insight">${state.snapshots.length} context snapshots</div><button class="secondary" id="newSnapshotBtn" style="margin-top:10px">◇ Save mental context</button></div><div class="card"><div class="recordType">COGNITIVE SIGNALS</div><div class="topline"><span>? → insight / distinction</span><b>${t.length}</b></div><div class="topline" style="margin-top:7px"><span>Incubation candidates</span><b>${inc.length}</b></div><div class="topline" style="margin-top:7px"><span>Repeated-question nodes</span><b>${fr.length}</b></div><p class="small">These are observations and low-confidence hypotheses, never diagnoses or fixed learner labels.</p></div><div class="card"><div class="recordType">RECENT WORKSPACE SNAPSHOTS</div>${latest.length?latest.map(s=>`<div class="divider"></div><div class="small">${new Date(s.timestamp).toLocaleString()}</div><b>${path(s.nodeId)}</b>${s.current?`<div>${esc(s.current)}</div>`:''}${s.openQuestion?`<div class="small">? ${esc(s.openQuestion)}</div>`:''}${s.nextReturn?`<div class="small">↩ ${esc(s.nextReturn)}</div>`:''}`).join(''):'<div class="muted" style="margin-top:8px">No snapshots yet.</div>'}</div><div class="card"><div class="recordType">PORTABLE DATA</div><p class="muted">Core history and cognitive extensions are exported together. Future UIs can rebuild views from the same durable records.</p><button class="secondary" id="fullExportBtn">Export full portable bundle</button></div>`;document.getElementById('newSnapshotBtn').onclick=openSnapshotForm;document.getElementById('fullExportBtn').onclick=downloadBundle}
function populateNodes(){const sel=document.getElementById('snapshotNode');if(!sel)return;sel.innerHTML='<option value="">No context</option>'+Object.values(CORE.db.nodes).sort((a,b)=>CORE.pathOf(a.id).join(' ').localeCompare(CORE.pathOf(b.id).join(' '))).map(n=>`<option value="${n.id}">${path(n.id)}</option>`).join('')}
function openSnapshotForm(){populateNodes();const a=active();document.getElementById('snapshotNode').value=a?.nodeId||'';document.getElementById('snapshotCurrent').value=a?.content||'';document.getElementById('snapshotHolding').value='';document.getElementById('snapshotQuestion').value='';document.getElementById('snapshotReturn').value=a?.position||'';document.querySelectorAll('[name="friction"]').forEach(x=>x.checked=false);document.getElementById('snapshotForm').classList.remove('hidden')}
function saveSnapshotFromUI(){const a=active();appendSnapshot({sessionId:a?.sessionId||null,nodeId:document.getElementById('snapshotNode').value||a?.nodeId||null,current:document.getElementById('snapshotCurrent').value.trim(),holding:document.getElementById('snapshotHolding').value.trim(),openQuestion:document.getElementById('snapshotQuestion').value.trim(),nextReturn:document.getElementById('snapshotReturn').value.trim(),friction:[...document.querySelectorAll('[name="friction"]:checked')].map(x=>x.value)});document.getElementById('snapshotForm').classList.add('hidden');renderUnderground()}
function addSessionContextButton(){const thought=document.getElementById('thoughtBtn');if(!thought||document.getElementById('workspaceBtn'))return;const b=document.createElement('button');b.className='ghost';b.id='workspaceBtn';b.textContent='◇ Context';thought.parentElement.appendChild(b);b.onclick=()=>{showUnderground();setTimeout(openSnapshotForm,0)}}
function addResumeContext(){const home=document.getElementById('home');if(!home||document.getElementById('mentalContextCard'))return;const s=state.snapshots.slice().sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp))[0];if(!s)return;const card=document.createElement('div');card.id='mentalContextCard';card.className='card';card.innerHTML=`<div class="small">LAST MENTAL CONTEXT · ${new Date(s.timestamp).toLocaleString()}</div><b>${path(s.nodeId)}</b>${s.current?`<div style="margin-top:6px">${esc(s.current)}</div>`:''}${s.openQuestion?`<div class="small" style="margin-top:6px">? ${esc(s.openQuestion)}</div>`:''}${s.nextReturn?`<div class="small">Next: ${esc(s.nextReturn)}</div>`:''}`;const label=home.querySelector('.sectionLabel');if(label)home.insertBefore(card,label)}
function wire(){populateNodes();document.getElementById('undergroundBtn')?.addEventListener('click',showUnderground);document.getElementById('undergroundBack')?.addEventListener('click',closeUnderground);document.getElementById('snapshotSave')?.addEventListener('click',saveSnapshotFromUI);document.getElementById('snapshotCancel')?.addEventListener('click',()=>document.getElementById('snapshotForm').classList.add('hidden'));const exp=document.getElementById('exportBtn');if(exp)exp.onclick=downloadBundle;const imp=document.getElementById('importBtn');if(imp)imp.onclick=async()=>{const f=document.getElementById('importFile').files[0];if(!f)return;try{await importBundle(f);location.reload()}catch(e){alert('Import failed')}};addSessionContextButton();addResumeContext();new MutationObserver(()=>{addSessionContextButton();if(!document.getElementById('mentalContextCard'))addResumeContext()}).observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
window.LearningCognitiveV4={EXT_KEY,EXT_SCHEMA,state,appendSnapshot,annotate,refreshHypotheses,bundle,mergeExtension};
})();