(()=>{
const D=window.LearningDB;if(!D)return;const db=D.db,esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function active(){try{return JSON.parse(localStorage.getItem(D.ACTIVE_KEY)||'null')}catch(e){return null}}
function latestWorkspace(nodeId){return db.records.filter(r=>r.type==='workspace_snapshot'&&(!nodeId||r.nodeId===nodeId)).sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp))[0]||null}
function addContextButton(){const thought=document.getElementById('thoughtBtn');if(!thought||document.getElementById('workspaceBtn'))return;const b=document.createElement('button');b.className='ghost';b.id='workspaceBtn';b.textContent='◇ Save context';thought.parentElement.appendChild(b);b.onclick=openWorkspace}
function ensurePanel(){if(document.getElementById('workspacePanel'))return;const sec=document.createElement('section');sec.id='workspacePanel';sec.className='hidden';sec.innerHTML=`<button class="back" id="workspaceBack">← Back</button><div class="small">EXTERNAL WORKING MEMORY</div><h2>Save the mental context</h2><p class="muted">全部を頭に持ったまま終えなくて大丈夫です。次回、ここから思考を復元できます。</p><label>今、何を理解しようとしている？</label><textarea id="wsCurrent" rows="3"></textarea><label>今、頭に置いているもの <span class="small">任意</span></label><textarea id="wsHolding" rows="4" placeholder="前提・用語・比較対象など"></textarea><label>未解決の問い <span class="small">任意</span></label><textarea id="wsQuestion" rows="3"></textarea><label>次に戻る場所 <span class="small">任意</span></label><input id="wsNext" placeholder="p.184 / この図 / この問いから"><button class="primary" id="wsSave" style="margin-top:20px">Save mental context</button>`;document.querySelector('.app').appendChild(sec);document.getElementById('workspaceBack').onclick=()=>showSession();document.getElementById('wsSave').onclick=saveWorkspace}
function hideMain(){document.querySelectorAll('.app>section').forEach(x=>x.classList.add('hidden'))}
function showSession(){document.getElementById('workspacePanel')?.classList.add('hidden');document.getElementById('session')?.classList.remove('hidden')}
function openWorkspace(){ensurePanel();const a=active();if(!a)return;const prev=latestWorkspace(a.nodeId);document.getElementById('wsCurrent').value=a.content||prev?.metadata?.current||'';document.getElementById('wsHolding').value=prev?.metadata?.holding||'';document.getElementById('wsQuestion').value=prev?.metadata?.question||'';document.getElementById('wsNext').value=a.position||prev?.metadata?.next||'';hideMain();document.getElementById('workspacePanel').classList.remove('hidden')}
function saveWorkspace(){const a=active();if(!a)return;const meta={current:document.getElementById('wsCurrent').value.trim(),holding:document.getElementById('wsHolding').value.trim(),question:document.getElementById('wsQuestion').value.trim(),next:document.getElementById('wsNext').value.trim(),engineVersion:'cognitive-v4'};D.addRecord('workspace_snapshot',{nodeId:a.nodeId,sessionId:a.sessionId,content:meta.current,metadata:meta});showSession();const t=document.getElementById('toast');if(t){t.textContent='Mental context saved';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1000)}}
function addResumeContext(){const home=document.getElementById('home');if(!home||document.getElementById('mentalContextCard'))return;const rec=latestWorkspace();if(!rec)return;const card=document.createElement('div');card.id='mentalContextCard';card.className='card';const m=rec.metadata||{};card.innerHTML=`<div class="small">LAST MENTAL CONTEXT · ${new Date(rec.timestamp).toLocaleString()}</div><b>${esc(D.pathOf(rec.nodeId).join(' › '))}</b>${m.current?`<div style="margin-top:6px">${esc(m.current)}</div>`:''}${m.question?`<div class="small" style="margin-top:6px">? ${esc(m.question)}</div>`:''}${m.next?`<div class="small">Next: ${esc(m.next)}</div>`:''}`;const continueLabel=home.querySelector('.sectionLabel');if(continueLabel)home.insertBefore(card,continueLabel)}
function observe(){addContextButton();addResumeContext();const mo=new MutationObserver(()=>{addContextButton();if(!document.getElementById('mentalContextCard'))addResumeContext()});mo.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observe);else observe();
})();