(()=>{
const CORE=window.LearningDB,V4=window.LearningCognitiveV4;if(!CORE)return;
const KEY='learningOS_cognitive_v5',SCHEMA='cognitive-extension/2.0';
const uid=(p='v5')=>p+'_'+(crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random().toString(36).slice(2));
const now=()=>new Date().toISOString();
const empty=()=>({schema:SCHEMA,createdAt:now(),updatedAt:now(),stateMarks:[],processNotes:[],hypotheses:[],modelVersions:[{id:'growth_1',createdAt:now(),name:'Learning OS Cognitive Growth Engine',rulesVersion:'2.0'}],dismissedHypotheses:[]});
let state;try{state=JSON.parse(localStorage.getItem(KEY)||'null')||empty()}catch(e){state=empty()}
for(const [k,v] of Object.entries({stateMarks:[],processNotes:[],hypotheses:[],modelVersions:[],dismissedHypotheses:[]}))if(!Array.isArray(state[k]))state[k]=v;
state.schema=SCHEMA;
const save=()=>{state.updatedAt=now();localStorage.setItem(KEY,JSON.stringify(state))};
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const path=id=>esc(CORE.pathOf(id).join(' › '));
const recs=()=>CORE.db.records.slice().sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp));
const sessions=()=>Object.values(CORE.db.sessions);
const active=()=>{try{return JSON.parse(localStorage.getItem(CORE.ACTIVE_KEY)||'null')}catch(e){return null}};
function addStateMark(mark){const a=active(),x={id:uid('state'),timestamp:now(),nodeId:mark.nodeId||a?.nodeId||null,sessionId:mark.sessionId||a?.sessionId||null,effort:mark.effort||null,ease:mark.ease||null,focus:mark.focus||null,note:mark.note||'',schemaVersion:1};state.stateMarks.push(x);save();CORE.addRecord('learning_state',{nodeId:x.nodeId,sessionId:x.sessionId,content:x.note,metadata:{stateMarkId:x.id,effort:x.effort,ease:x.ease,focus:x.focus,engineVersion:'growth-v1'}});return x}
function processTrace(sessionId){const rs=CORE.db.records.filter(r=>r.sessionId===sessionId).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp));return rs.filter(r=>!['session_start','session_end','workspace_snapshot'].includes(r.type)).map(r=>({id:r.id,type:r.type,timestamp:r.timestamp,content:r.content||''}))}
function allTraces(){return sessions().map(s=>({session:s,trace:processTrace(s.id)})).filter(x=>x.trace.length)}
function transitions(){const out=[];for(const {session,trace} of allTraces()){for(let i=0;i<trace.length;i++){if(!['question','revisit'].includes(trace[i].type))continue;const j=trace.slice(i+1).find(x=>['distinction','gotit'].includes(x.type));if(j)out.push({nodeId:session.nodeId,sessionId:session.id,from:trace[i],to:j,minutes:(new Date(j.timestamp)-new Date(trace[i].timestamp))/60000,between:trace.filter(x=>new Date(x.timestamp)>new Date(trace[i].timestamp)&&new Date(x.timestamp)<new Date(j.timestamp)).map(x=>x.type)})}}return out}
function openLoops(){const all=recs(),out=[];for(let i=0;i<all.length;i++){const r=all[i];if(r.type!=='question')continue;const resolved=all.slice(i+1).find(x=>x.nodeId===r.nodeId&&['gotit','distinction'].includes(x.type));if(!resolved&&Date.now()-new Date(r.timestamp)>12*3600000)out.push(r)}return out.slice(-30).reverse()}
function incubationChains(){const all=recs(),out=[];for(let i=0;i<all.length;i++){const r=all[i];if(!['question','revisit'].includes(r.type))continue;const later=all.slice(i+1).find(x=>x.nodeId===r.nodeId&&['gotit','distinction'].includes(x.type));if(later){const hrs=(new Date(later.timestamp)-new Date(r.timestamp))/3600000;if(hrs>=6)out.push({nodeId:r.nodeId,from:r,to:later,hours:hrs})}}return out}
function languageCandidates(){const rx=/(全然|いつも|絶対|まったく|全く|苦手|できない|分からない|わからない|無理|always|never|can't|cannot|bad at|don't understand|do not understand)/i;return CORE.db.records.filter(r=>r.content&&rx.test(r.content)&&['thought','question','reflection'].includes(r.type)).slice(-40).reverse().map(r=>({record:r,prompt:/いつも|絶対|always|never/i.test(r.content)?'いつも？ それとも特定の状況？':/苦手|bad at|できない|can.?t|cannot/i.test(r.content)?'具体的には、何をしようとした時に何が起きる？':'どの部分が、どのように分からない？'}))}
function groundingShifts(){const gs=V4?.state?.groundings||[];const out=[];for(const g of gs){const later=CORE.db.records.filter(r=>r.nodeId===g.nodeId&&new Date(r.timestamp)>new Date(g.timestamp)&&['distinction','gotit'].includes(r.type)).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp))[0];if(later)out.push({grounding:g,to:later,minutes:(new Date(later.timestamp)-new Date(g.timestamp))/60000})}return out}
function effortEase(){const by={};state.stateMarks.forEach(m=>{if(!m.nodeId)return;(by[m.nodeId]||(by[m.nodeId]=[])).push(m)});return Object.entries(by).map(([nodeId,marks])=>{marks.sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp));const first=marks[0],last=marks.at(-1);return {nodeId,count:marks.length,first,last,improved:marks.length>=2&&Number(last.ease||0)>Number(first.ease||0)}}).filter(x=>x.count>=2)}
function candidatePatterns(){const ts=transitions(),freq={};ts.forEach(t=>{const key=t.between.join('→')||'(direct)';freq[key]=(freq[key]||0)+1});return Object.entries(freq).filter(([,n])=>n>=2).sort((a,b)=>b[1]-a[1]).map(([sequence,count])=>({sequence,count,confidence:count>=5?'medium':'low'}))}
function refresh(){const generated=[];candidatePatterns().forEach(p=>generated.push({kind:'process_pattern',key:p.sequence,confidence:p.confidence,evidenceCount:p.count,text:`${p.sequence} が ? / ↩ から理解への途中で繰り返し現れています。`}));groundingShifts().forEach(g=>generated.push({kind:'grounding_transition',key:g.grounding.id,confidence:'low',nodeId:g.grounding.nodeId,text:'Grounding記録の後に理解/区別イベントがありました。因果関係ではなく候補です。'}));effortEase().filter(x=>x.improved).forEach(x=>generated.push({kind:'effort_to_ease',key:x.nodeId,confidence:'low',nodeId:x.nodeId,text:'同じテーマで「楽さ」の自己記録が上昇しています。'}));const exists=new Set(state.hypotheses.map(x=>x.kind+'|'+x.key));generated.forEach(g=>{if(!exists.has(g.kind+'|'+g.key))state.hypotheses.push({id:uid('hyp'),createdAt:now(),modelVersion:'growth_1',status:'candidate',...g})});save();return generated}
function hideAll(){document.querySelectorAll('.app>section').forEach(x=>x.classList.add('hidden'))}
function ensureUI(){const home=document.getElementById('home');if(!home)return;if(!document.getElementById('growthBtn')){const tb=home.querySelector('.toolbar'),b=document.createElement('button');b.className='chip';b.id='growthBtn';b.textContent='How you changed';tb?.insertBefore(b,document.getElementById('dataBtn'));b.onclick=showGrowth}
if(!document.getElementById('growth')){const sec=document.createElement('section');sec.id='growth';sec.className='hidden';sec.innerHTML=`<button class="back" id="growthBack">← Home</button><div class="small">HOW YOU CHANGED</div><h2>Learning itself can grow</h2><p class="muted">成績や学習時間だけでなく、「問い方・区別・つながり・再訪・具体化・楽さ」の変化を見ます。表示は診断ではなく履歴からの観察です。</p><div id="growthBody"></div>`;document.querySelector('.app').appendChild(sec);document.getElementById('growthBack').onclick=()=>{hideAll();document.getElementById('home').classList.remove('hidden')}}
if(!document.getElementById('statePanel')){const sec=document.createElement('section');sec.id='statePanel';sec.className='hidden';sec.innerHTML=`<button class="back" id="stateBack">← Learning</button><div class="small">LEARNING STATE · OPTIONAL</div><h2>How does it feel now?</h2><p class="muted">毎回入力する必要はありません。同じ内容が「努力が必要 → 自然にできる」へ変わった時だけ残すための記録です。</p><label>Effort</label><select id="stateEffort"><option value="">—</option><option value="4">かなり努力が必要</option><option value="3">努力が必要</option><option value="2">少し意識する</option><option value="1">ほぼ努力なし</option></select><label>Ease</label><select id="stateEase"><option value="">—</option><option value="1">まだ重い</option><option value="2">少し楽</option><option value="3">かなり楽</option><option value="4">自然にできる</option></select><label>一言 <span class="small">任意</span></label><textarea id="stateNote" rows="3" placeholder="例：前は図を見ないと無理だったが、今は頭の中で向きが分かる"></textarea><button class="primary" id="stateSave" style="margin-top:18px">Save state</button>`;document.querySelector('.app').appendChild(sec);document.getElementById('stateBack').onclick=()=>{hideAll();document.getElementById('session').classList.remove('hidden')};document.getElementById('stateSave').onclick=()=>{addStateMark({effort:document.getElementById('stateEffort').value,ease:document.getElementById('stateEase').value,note:document.getElementById('stateNote').value.trim()});hideAll();document.getElementById('session').classList.remove('hidden');toast('State remembered')}}
const thought=document.getElementById('thoughtBtn');if(thought&&!document.getElementById('stateBtn')){const b=document.createElement('button');b.className='ghost';b.id='stateBtn';b.textContent='◎ State';thought.parentElement.appendChild(b);b.onclick=()=>{hideAll();document.getElementById('statePanel').classList.remove('hidden')}}}
function toast(s){const t=document.getElementById('toast');if(!t)return;t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),900)}
function showGrowth(){refresh();hideAll();document.getElementById('growth').classList.remove('hidden');renderGrowth()}
function renderGrowth(){const body=document.getElementById('growthBody'),ts=transitions(),incs=incubationChains(),loops=openLoops(),lc=languageCandidates(),gs=groundingShifts(),ease=effortEase(),connections=CORE.db.records.filter(r=>r.type==='connection').length,dist=CORE.db.records.filter(r=>r.type==='distinction').length,thoughts=CORE.db.records.filter(r=>r.type==='thought').length;const patterns=candidatePatterns();body.innerHTML=`<div class="card"><div class="recordType">GROWTH SIGNALS</div><div class="topline"><span>? / ↩ → 💡 / ≠</span><b>${ts.length}</b></div><div class="topline" style="margin-top:7px"><span>Connections created</span><b>${connections}</b></div><div class="topline" style="margin-top:7px"><span>Distinctions noticed</span><b>${dist}</b></div><div class="topline" style="margin-top:7px"><span>Thoughts externalized</span><b>${thoughts}</b></div><div class="topline" style="margin-top:7px"><span>Grounding → later insight candidates</span><b>${gs.length}</b></div></div><div class="card"><div class="recordType">OPEN LOOPS</div><div class="insight">${loops.length} unresolved questions</div>${loops.slice(0,6).map(r=>`<div class="divider"></div><div class="small">${new Date(r.timestamp).toLocaleString()}</div><b>${path(r.nodeId)}</b>${r.content?`<div>${esc(r.content)}</div>`:''}`).join('')||'<p class="muted">No old unresolved questions detected.</p>'}</div><div class="card"><div class="recordType">INCUBATION / RE-ENCOUNTER</div><div class="insight">${incs.length} possible chains</div>${incs.slice(-5).reverse().map(x=>`<div class="divider"></div><b>${path(x.nodeId)}</b><div class="small">${Math.round(x.hours)}h between ${x.from.type} and ${x.to.type}</div>`).join('')||'<p class="muted">Not enough history yet.</p>'}</div><div class="card"><div class="recordType">PROCESS PATTERNS · TENTATIVE</div>${patterns.slice(0,6).map(p=>`<div class="divider"></div><b>${esc(p.sequence)}</b><div class="small">observed ${p.count} times · confidence ${p.confidence}</div>`).join('')||'<p class="muted">Repeated transformation patterns will appear after more sessions.</p>'}</div><div class="card"><div class="recordType">EFFORT → EASE</div>${ease.filter(x=>x.improved).slice(0,6).map(x=>`<div class="divider"></div><b>${path(x.nodeId)}</b><div class="small">ease ${x.first.ease||'?'} → ${x.last.ease||'?'} across ${x.count} state marks</div>`).join('')||'<p class="muted">Use ◎ State only when you notice something becoming easier.</p>'}</div><div class="card"><div class="recordType">LANGUAGE PRECISION · GRINDER LENS</div><p class="small">自己評価を事実へ固定せず、必要なら具体化する候補です。</p>${lc.slice(0,5).map(x=>`<div class="divider"></div><div>${esc(x.record.content)}</div><div class="small">↳ ${esc(x.prompt)}</div>`).join('')||'<p class="muted">No broad self-statements detected.</p>'}</div>`}
function portableBundle(){return {bundleType:'learning-os-portable-bundle',bundleVersion:3,exportedAt:now(),core:CORE.db,extensions:{cognitiveV4:V4?.state||null,cognitiveV5:state},compatibility:{principle:'evidence-durable-hypotheses-replaceable',coreSchema:CORE.SCHEMA_VERSION,cognitiveV4:V4?.EXT_SCHEMA||null,cognitiveV5:SCHEMA}}}
function exportAll(){const blob=new Blob([JSON.stringify(portableBundle(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`learning-os-portable-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function mergeV5(x){if(!x)return;for(const k of ['stateMarks','processNotes','hypotheses','modelVersions']){const ids=new Set(state[k].map(v=>v.id));(x[k]||[]).forEach(v=>{if(v?.id&&!ids.has(v.id))state[k].push(v)})}save()}
async function importAll(file){const x=JSON.parse(await file.text());if(x?.bundleType==='learning-os-portable-bundle'){if(x.core)CORE.merge(x.core);if(x.extensions?.cognitiveV4&&V4?.mergeExtension)V4.mergeExtension(x.extensions.cognitiveV4);if(x.extensions?.cognitiveV5)mergeV5(x.extensions.cognitiveV5);return}CORE.merge(x)}
function patchData(){const exp=document.getElementById('exportBtn');if(exp)exp.onclick=exportAll;const imp=document.getElementById('importBtn');if(imp)imp.onclick=async()=>{const f=document.getElementById('importFile')?.files?.[0];if(!f)return toast('ファイルを選んでください');try{await importAll(f);toast('Imported');setTimeout(()=>location.reload(),500)}catch(e){toast('Import failed')}}}
function observe(){ensureUI();patchData();new MutationObserver(()=>ensureUI()).observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observe);else observe();
window.LearningCognitiveV5={KEY,SCHEMA,state,addStateMark,processTrace,transitions,openLoops,incubationChains,languageCandidates,groundingShifts,candidatePatterns,refresh,portableBundle,mergeV5};
})();