(()=>{
const CORE=window.LearningDB,V4=window.LearningCognitiveV4,V5=window.LearningCognitiveV5;
if(!CORE)return;
const KEY='learningOS_control_v8',SCHEMA='control-extension/1.0';
const uid=(p='ctl')=>p+'_'+(crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random().toString(36).slice(2));
const now=()=>new Date().toISOString();
const empty=()=>({schema:SCHEMA,createdAt:now(),updatedAt:now(),goals:[],worldModelSnapshots:[],valueJudgments:[],actionPlans:[],actionOutcomes:[],modelVersions:[{id:'control_1',createdAt:now(),name:'Learning Control Loop',inspiration:'Albus RCS',rulesVersion:'1.0'}]});
let state;try{state=JSON.parse(localStorage.getItem(KEY)||'null')||empty()}catch(e){state=empty()}
for(const k of ['goals','worldModelSnapshots','valueJudgments','actionPlans','actionOutcomes','modelVersions'])if(!Array.isArray(state[k]))state[k]=[];
state.schema=SCHEMA;
const save=()=>{state.updatedAt=now();localStorage.setItem(KEY,JSON.stringify(state))};
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const path=id=>esc(CORE.pathOf(id).join(' › '));
const active=()=>{try{return JSON.parse(localStorage.getItem(CORE.ACTIVE_KEY)||'null')}catch(e){return null}};
function addGoal(x){const g={id:uid('goal'),timestamp:now(),level:x.level||'topic',nodeId:x.nodeId||null,text:x.text||'',status:'active',parentGoalId:x.parentGoalId||null,schemaVersion:1};state.goals.push(g);save();CORE.addRecord('goal',{nodeId:g.nodeId,content:g.text,metadata:{goalId:g.id,level:g.level,engineVersion:'control-v1'}});return g}
function observe(nodeId){const rs=CORE.db.records.filter(r=>!nodeId||r.nodeId===nodeId).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp));const recent=rs.slice(-60),counts={};recent.forEach(r=>counts[r.type]=(counts[r.type]||0)+1);const questions=recent.filter(r=>r.type==='question'),insights=recent.filter(r=>['gotit','distinction'].includes(r.type));const last=recent.at(-1)||null;return {nodeId:nodeId||null,timestamp:now(),counts,questionCount:questions.length,insightCount:insights.length,lastRecordId:last?.id||null,lastType:last?.type||null,evidenceRecordIds:recent.map(r=>r.id)}}
function buildWorldModel(nodeId){const obs=observe(nodeId),grounds=(V4?.state?.groundings||[]).filter(g=>!nodeId||g.nodeId===nodeId),snaps=(V4?.state?.snapshots||[]).filter(s=>!nodeId||s.nodeId===nodeId),marks=(V5?.state?.stateMarks||[]).filter(s=>!nodeId||s.nodeId===nodeId);const unresolved=CORE.db.records.filter(r=>r.nodeId===nodeId&&r.type==='question').filter(q=>!CORE.db.records.some(r=>r.nodeId===nodeId&&new Date(r.timestamp)>new Date(q.timestamp)&&['gotit','distinction'].includes(r.type))).length;return {id:uid('world'),timestamp:now(),nodeId:nodeId||null,observation:obs,groundingCount:grounds.length,workspaceCount:snaps.length,stateMarkCount:marks.length,unresolvedQuestions:unresolved,summary:{studied:obs.evidenceRecordIds.length>0,uncertainty:unresolved>0?'present':'not-observed',grounded:grounds.length>0,contextExternalized:snaps.length>0},schemaVersion:1}}
function saveWorldModel(nodeId){const w=buildWorldModel(nodeId);state.worldModelSnapshots.push(w);save();return w}
function judge(nodeId){const w=buildWorldModel(nodeId),reasons=[];let score=0;if(w.unresolvedQuestions){score+=3;reasons.push(`${w.unresolvedQuestions} unresolved question(s)`)}if(w.observation.questionCount>=2&&!w.groundingCount){score+=2;reasons.push('repeated questions with no grounding route saved')}if(w.workspaceCount){score+=1;reasons.push('mental context exists, so resuming can be cheap')}if(w.observation.insightCount){score+=1;reasons.push('recent insight/distinction evidence exists')}const j={id:uid('value'),timestamp:now(),nodeId,score,reasons,status:'candidate',modelVersion:'control_1',schemaVersion:1};state.valueJudgments.push(j);save();return j}
function suggestAction(nodeId){const w=buildWorldModel(nodeId),j=judge(nodeId);let action='Continue for a short focused session',kind='continue',why='There is learning history here.';if(w.unresolvedQuestions&&w.groundingCount===0){kind='ground';action='🧩 Ground one unresolved question in a concrete situation, action, diagram, or contrast';why='Unresolved question evidence exists and no grounding route is saved.'}else if(w.unresolvedQuestions){kind='revisit';action='↩️ Revisit one unresolved question and record what is different now';why='An open loop is still visible in the durable record.'}else if(w.workspaceCount){kind='resume';action='🧠 Resume from the latest mental context';why='A workspace snapshot can reduce reconstruction cost.'}const p={id:uid('plan'),timestamp:now(),nodeId,kind,action,why,valueJudgmentId:j.id,status:'suggested',schemaVersion:1};state.actionPlans.push(p);save();return p}
function recordOutcome(planId,result,note=''){const p=state.actionPlans.find(x=>x.id===planId),o={id:uid('outcome'),timestamp:now(),planId,nodeId:p?.nodeId||null,result,note,schemaVersion:1};state.actionOutcomes.push(o);if(p)p.status='observed';save();CORE.addRecord('action_outcome',{nodeId:o.nodeId,content:note||result,metadata:{planId,outcomeId:o.id,result,engineVersion:'control-v1'}});return o}
function hideAll(){document.querySelectorAll('.app>section').forEach(s=>s.classList.add('hidden'))}
function ensureUI(){const home=document.getElementById('home');if(!home)return;if(!document.getElementById('controlBtn')){const b=document.createElement('button');b.className='chip';b.id='controlBtn';b.innerHTML='🌍 <span>Model</span>';home.querySelector('.toolbar')?.insertBefore(b,document.getElementById('dataBtn'));b.onclick=show}
if(!document.getElementById('control')){const sec=document.createElement('section');sec.id='control';sec.className='hidden';sec.innerHTML=`<button class="back" id="controlBack">← Home</button><div class="small">🌍 LEARNING CONTROL LOOP</div><h2>Observe → Model → Choose → Act</h2><p class="muted">学習履歴から現在地を組み立て、次の一手の候補を出します。命令や診断ではなく、根拠を確認できる再計算可能なモデルです。</p><label>🎯 見たい学習テーマ</label><select id="controlNode"></select><div id="controlBody"></div>`;document.querySelector('.app').appendChild(sec);document.getElementById('controlBack').onclick=()=>{hideAll();document.getElementById('home').classList.remove('hidden')};document.getElementById('controlNode').onchange=render}}
function fillNodes(){const s=document.getElementById('controlNode');if(!s)return;const old=s.value;s.innerHTML='<option value="">全体</option>'+Object.values(CORE.db.nodes).map(n=>`<option value="${n.id}">${path(n.id)}</option>`).join('');if(old)s.value=old}
function show(){hideAll();document.getElementById('control').classList.remove('hidden');fillNodes();render()}
function render(){const body=document.getElementById('controlBody');if(!body)return;const nodeId=document.getElementById('controlNode')?.value||null,w=buildWorldModel(nodeId),latestGoal=state.goals.filter(g=>!nodeId||g.nodeId===nodeId).at(-1),lastPlan=state.actionPlans.filter(p=>!nodeId||p.nodeId===nodeId).at(-1);body.innerHTML=`<div class="control-loop"><span>👁️ Observe</span><i>→</i><span>🌍 Model</span><i>→</i><span>⚖️ Choose</span><i>→</i><span>▶️ Act</span><i>↺</i></div><div class="card"><div class="recordType">👁️ OBSERVATION · DURABLE EVIDENCE</div><div class="topline"><span>Recent evidence</span><b>${w.observation.evidenceRecordIds.length}</b></div><div class="topline" style="margin-top:7px"><span>Questions</span><b>${w.observation.questionCount}</b></div><div class="topline" style="margin-top:7px"><span>Insights / distinctions</span><b>${w.observation.insightCount}</b></div></div><div class="card"><div class="recordType">🌍 WORLD MODEL · REBUILDABLE</div><div class="small">Unresolved questions: ${w.unresolvedQuestions}</div><div class="small">Grounding routes: ${w.groundingCount}</div><div class="small">Mental contexts: ${w.workspaceCount}</div><div class="small">State marks: ${w.stateMarkCount}</div><button class="secondary" id="saveWorldBtn" style="margin-top:12px">📸 Save model snapshot</button></div><div class="card"><div class="recordType">🎯 GOAL · OPTIONAL</div>${latestGoal?`<div>${esc(latestGoal.text)}</div><div class="small">${esc(latestGoal.level)}</div>`:'<p class="muted">No goal saved for this context.</p>'}<div class="plusrow"><input id="goalText" placeholder="例：/v/ と /f/ を聞き分けられる"><button id="goalAdd">＋</button></div></div><div class="card"><div class="recordType">⚖️ VALUE → ▶️ NEXT ACTION</div><p class="small">「価値」は人格評価ではなく、今このテーマへ戻る理由の候補です。</p><button class="primary" id="suggestBtn">🧭 次の一手を考える</button><div id="suggestion">${lastPlan?`<div class="divider"></div><b>${esc(lastPlan.action)}</b><div class="small">${esc(lastPlan.why)}</div><div class="row" style="margin-top:10px"><button class="secondary grow" data-outcome="helped" data-plan="${lastPlan.id}">✓ Helped</button><button class="secondary grow" data-outcome="not_helped" data-plan="${lastPlan.id}">↺ Not yet</button></div>`:''}</div></div>`;document.getElementById('saveWorldBtn').onclick=()=>{saveWorldModel(nodeId);render()};document.getElementById('goalAdd').onclick=()=>{const t=document.getElementById('goalText').value.trim();if(t){addGoal({nodeId,text:t,level:nodeId?'topic':'domain'});render()}};document.getElementById('suggestBtn').onclick=()=>{suggestAction(nodeId);render()};body.querySelectorAll('[data-outcome]').forEach(b=>b.onclick=()=>{recordOutcome(b.dataset.plan,b.dataset.outcome);render()})}
function portable(){return {schema:SCHEMA,...state}}
function merge(x){if(!x)return;for(const k of ['goals','worldModelSnapshots','valueJudgments','actionPlans','actionOutcomes','modelVersions']){const ids=new Set(state[k].map(v=>v.id));(x[k]||[]).forEach(v=>{if(v?.id&&!ids.has(v.id))state[k].push(v)})}save()}
function wire(){ensureUI();fillNodes()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
window.LearningControlV8={KEY,SCHEMA,state,observe,buildWorldModel,saveWorldModel,judge,suggestAction,recordOutcome,portable,merge};
})();