(()=>{
const DB_KEY='learningOS_db_v3',ACTIVE_KEY='learningOS_active_v3',LEGACY_BACKUP_KEY='learningOS_legacy_backup_v1',SCHEMA_VERSION=3;
const oldKeys=['learningOS_pwa_v1','learningOS_v03','learningOS_v02','learningOS_v01'];
const oldActiveKeys=['learningOS_active_pwa_v1','learningOS_active_v03','learningOS_active_v02'];
const uid=(p='id')=>p+'_'+(crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random().toString(36).slice(2));
const nowISO=()=>new Date().toISOString();
const emptyDB=()=>({schemaVersion:SCHEMA_VERSION,meta:{createdAt:nowISO(),updatedAt:nowISO(),migrations:[]},nodes:{},sessions:{},records:[],relations:[]});
function findOrCreatePath(target,names){let parent=null,last=null;names.filter(Boolean).forEach((name,i)=>{let found=Object.values(target.nodes).find(n=>n.parentId===parent&&n.name===name);if(!found){const id=uid('node'),ts=nowISO();found={id,name,parentId:parent,type:i===0?'area':i===1?'thread':'topic',createdAt:ts,updatedAt:ts};target.nodes[id]=found}parent=found.id;last=found.id});return last}
function migrateLegacyObject(old,source){const out=emptyDB();if(!old)return out;const sessions=Array.isArray(old.sessions)?old.sessions:[];sessions.forEach(s=>{const area=s.topic||'Legacy Learning',content=s.content||s.focus||'General',nid=findOrCreatePath(out,[area,content]),sid=s.id||uid('sess'),startAt=new Date(s.start||s.startAt||Date.now()).toISOString(),endAt=(s.end||s.endAt)?new Date(s.end||s.endAt).toISOString():null,dur=s.duration||s.durationSeconds||(endAt?Math.max(1,Math.round((new Date(endAt)-new Date(startAt))/1000)):null);out.sessions[sid]={id:sid,nodeId:nid,startAt,endAt,durationSeconds:dur,content,position:s.endPosition||s.position||s.pos||'',outcome:s.outcome||'',createdAt:startAt,updatedAt:endAt||startAt};out.records.push({id:uid('rec'),timestamp:startAt,type:'session_start',nodeId:nid,sessionId:sid,content,metadata:{legacySource:source},relations:[]});(s.events||[]).forEach(e=>{const map={confused:'question',important:'thought',gotit:'gotit',revisit:'revisit'};out.records.push({id:uid('rec'),timestamp:new Date(e.time||startAt).toISOString(),type:map[e.type]||e.type||'note',nodeId:nid,sessionId:sid,content:'',metadata:{legacySource:source},relations:[]})});if(s.outcome)out.records.push({id:uid('rec'),timestamp:endAt||startAt,type:'reflection',nodeId:nid,sessionId:sid,content:s.outcome,metadata:{legacySource:source},relations:[]});if(endAt)out.records.push({id:uid('rec'),timestamp:endAt,type:'session_end',nodeId:nid,sessionId:sid,content,metadata:{legacySource:source,durationSeconds:dur},relations:[]})});return out}
function mergeTwo(a,b){Object.assign(a.nodes,b.nodes);Object.assign(a.sessions,b.sessions);a.records.push(...b.records);a.relations.push(...b.relations);return a}
function normalizeDB(x){if(x&&x.schemaVersion===3&&x.nodes&&x.sessions&&Array.isArray(x.records))return x;return migrateLegacyObject(x,'import')}
function loadAndMigrate(){const existing=localStorage.getItem(DB_KEY);if(existing){try{return normalizeDB(JSON.parse(existing))}catch(e){}}
const snapshots={};oldKeys.forEach(k=>{const raw=localStorage.getItem(k);if(raw)snapshots[k]=raw});if(Object.keys(snapshots).length&&!localStorage.getItem(LEGACY_BACKUP_KEY))localStorage.setItem(LEGACY_BACKUP_KEY,JSON.stringify({savedAt:nowISO(),snapshots}));let out=emptyDB();for(const [k,raw] of Object.entries(snapshots)){try{out=mergeTwo(out,migrateLegacyObject(JSON.parse(raw),k))}catch(e){}}
out.meta.migrations.push({at:nowISO(),type:'legacy_to_v3',sources:Object.keys(snapshots)});localStorage.setItem(DB_KEY,JSON.stringify(out));
oldActiveKeys.forEach(k=>{const raw=localStorage.getItem(k);if(raw&&!localStorage.getItem(ACTIVE_KEY)){try{const a=JSON.parse(raw),rid=findOrCreatePath(out,[a.topic||'Legacy',a.content||a.focus||'General']),sid=uid('sess'),startAt=new Date(a.start||Date.now()).toISOString();out.sessions[sid]={id:sid,nodeId:rid,startAt,endAt:null,durationSeconds:null,content:a.content||a.focus||'',position:a.position||a.pos||'',createdAt:startAt,updatedAt:startAt};localStorage.setItem(ACTIVE_KEY,JSON.stringify({sessionId:sid,nodeId:rid,startAt,content:out.sessions[sid].content,position:out.sessions[sid].position}))}catch(e){}}});localStorage.setItem(DB_KEY,JSON.stringify(out));return out}
let db=loadAndMigrate();
function save(){db.schemaVersion=SCHEMA_VERSION;db.meta.updatedAt=nowISO();localStorage.setItem(DB_KEY,JSON.stringify(db))}
function node(id){return db.nodes[id]||null}
function children(id){return Object.values(db.nodes).filter(n=>n.parentId===id).sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''))}
function roots(){return Object.values(db.nodes).filter(n=>!n.parentId).sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''))}
function pathOf(id){const parts=[];let n=node(id),guard=0;while(n&&guard++<30){parts.unshift(n.name);n=n.parentId?node(n.parentId):null}return parts}
function rootIdOf(id){let n=node(id),last=id,guard=0;while(n&&guard++<30){last=n.id;n=n.parentId?node(n.parentId):null}return last}
function addNode(name,parentId=null,type=null){const id=uid('node'),ts=nowISO(),depth=parentId?pathOf(parentId).length:0;db.nodes[id]={id,name:name.trim(),parentId,type:type||(depth===0?'area':depth===1?'thread':'topic'),createdAt:ts,updatedAt:ts};save();return id}
function touchNode(id){let n=node(id),guard=0;while(n&&guard++<30){n.updatedAt=nowISO();n=n.parentId?node(n.parentId):null}}
function addRecord(type,{nodeId=null,sessionId=null,content='',metadata={},relations=[]}={}){const rec={id:uid('rec'),timestamp:nowISO(),type,nodeId,sessionId,content,metadata,relations};db.records.push(rec);if(nodeId)touchNode(nodeId);save();return rec}
function descendants(id){const out=[id];for(const c of children(id))out.push(...descendants(c.id));return out}
function sessionDuration(s){return s.durationSeconds||Math.max(0,((s.endAt?new Date(s.endAt):new Date())-new Date(s.startAt))/1000)}
function totalSeconds(id){const ids=new Set(descendants(id));return Object.values(db.sessions).filter(s=>ids.has(s.nodeId)).reduce((a,s)=>a+sessionDuration(s),0)}
function merge(incoming){const n=normalizeDB(incoming);Object.values(n.nodes).forEach(x=>{if(!db.nodes[x.id])db.nodes[x.id]=x});Object.values(n.sessions).forEach(x=>{if(!db.sessions[x.id])db.sessions[x.id]=x});const rids=new Set(db.records.map(r=>r.id));n.records.forEach(r=>{if(!rids.has(r.id))db.records.push(r)});const lids=new Set(db.relations.map(r=>r.id));(n.relations||[]).forEach(r=>{if(!lids.has(r.id))db.relations.push(r)});db.meta.migrations.push({at:nowISO(),type:'import_merge'});save()}
window.LearningDB={DB_KEY,ACTIVE_KEY,SCHEMA_VERSION,db,save,uid,nowISO,node,children,roots,pathOf,rootIdOf,addNode,touchNode,addRecord,descendants,sessionDuration,totalSeconds,merge};
})();