(()=>{
const q=id=>document.getElementById(id);
const hideAll=()=>document.querySelectorAll('.app>section').forEach(s=>s.classList.add('hidden'));
function addLegend(){const home=q('home');if(!home||q('visualLegendBtn'))return;const tb=home.querySelector('.toolbar');const b=document.createElement('button');b.className='chip';b.id='visualLegendBtn';b.innerHTML='🧭 <span>Legend</span>';tb?.insertBefore(b,q('dataBtn'));
const sec=document.createElement('section');sec.id='visualLegend';sec.className='hidden';sec.innerHTML=`<button class="back" id="visualLegendBack">← Home</button><div class="small">🧭 VISUAL VOCABULARY</div><h2>See it before you read it</h2><p class="muted">絵文字は装飾ではなく、Learning OS内で同じ意味を持つ認知記号です。</p><div class="symbolGrid"><div><b>💡</b><span>理解・Insight</span></div><div><b>❓</b><span>疑問・Open loop</span></div><div><b>⚡</b><span>驚き・Unexpected</span></div><div><b>≠</b><span>違い・Distinction</span></div><div><b>↩️</b><span>再訪・Revisit</span></div><div><b>💭</b><span>思考・Thought</span></div><div><b>🧠</b><span>Working memory / Context</span></div><div><b>🧩</b><span>Grounding / Concrete</span></div><div><b>🔗</b><span>Connection</span></div><div><b>🌿</b><span>Growth / Ease</span></div><div><b>🎯</b><span>Focus</span></div><div><b>⏳</b><span>Time</span></div><div><b>🗺️</b><span>Map</span></div><div><b>🧭</b><span>Context / Orientation</span></div><div><b>🔄</b><span>Reframe / Representation shift</span></div><div><b>⚖️</b><span>Compare / Contrast</span></div></div>`;document.querySelector('.app').appendChild(sec);b.onclick=()=>{hideAll();sec.classList.remove('hidden')};q('visualLegendBack').onclick=()=>{hideAll();home.classList.remove('hidden')};}
function decorateDynamic(){const g=q('growthBtn');if(g&&g.dataset.visual!=='1'){g.innerHTML='🌿 <span>Growth</span>';g.dataset.visual='1'}const s=q('stateBtn');if(s&&s.dataset.visual!=='1'){s.textContent='🌿 State';s.dataset.visual='1'}const w=q('workspaceBtn');if(w&&w.dataset.visual!=='1'){w.textContent='🧠 Context';w.dataset.visual='1'}}
function addSessionDock(){const session=q('session');if(!session||q('cognitiveDock'))return;const events=session.querySelector('.events');if(!events)return;const dock=document.createElement('div');dock.id='cognitiveDock';dock.className='cognitiveDock';dock.innerHTML=`<button data-jump="thought">💭<span>Thought</span></button><button data-jump="context">🧠<span>Context</span></button><button data-jump="ground">🧩<span>Ground</span></button><button data-jump="state">🌿<span>State</span></button>`;events.insertAdjacentElement('afterend',dock);
dock.querySelector('[data-jump="thought"]').onclick=()=>q('thoughtBtn')?.click();dock.querySelector('[data-jump="context"]').onclick=()=>q('workspaceBtn')?.click();dock.querySelector('[data-jump="state"]').onclick=()=>q('stateBtn')?.click();dock.querySelector('[data-jump="ground"]').onclick=()=>{q('workspaceBtn')?.click();setTimeout(()=>q('groundSituation')?.focus(),60)};}
function wire(){addLegend();decorateDynamic();addSessionDock();new MutationObserver(()=>{decorateDynamic();addSessionDock();if(!q('visualLegendBtn'))addLegend()}).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();