(()=>{
const CORE=window.LearningDB;if(!CORE)return;
const q=id=>document.getElementById(id),hideAll=()=>document.querySelectorAll('.app>section').forEach(s=>s.classList.add('hidden'));
const symbols={gotit:'💡',question:'❓',surprise:'⚡',distinction:'≠',revisit:'↩️',thought:'💭',connection:'🔗',grounding:'🧩',workspace_snapshot:'🧠',learning_state:'🌿',reflection:'✍️'};
function active(){try{return JSON.parse(localStorage.getItem(CORE.ACTIVE_KEY)||'null')}catch(e){return null}}
function ensureGrammar(){const session=q('session');if(!session)return;
 if(!q('visualFlow')){const flow=document.createElement('div');flow.id='visualFlow';flow.className='visualFlow card';flow.innerHTML=`<div class="flowStage"><span class="flowShape flow-pill">🎯</span><small>Focus</small></div><div class="flowArrow">→</div><div class="flowStage"><span class="flowShape flow-circle">❓</span><small>Notice</small></div><div class="flowArrow">→</div><div class="flowStage"><span class="flowShape flow-square">🧩</span><small>Work</small></div><div class="flowArrow">→</div><div class="flowStage"><span class="flowShape flow-circle">💡</span><small>Change</small></div>`;const timer=q('timer');timer?.insertAdjacentElement('afterend',flow)}
 if(!q('eventTrail')){const trail=document.createElement('div');trail.id='eventTrail';trail.className='eventTrail';const events=session.querySelector('.events');events?.insertAdjacentElement('beforebegin',trail)}
 decorateGeometry();renderTrail();}
function decorateGeometry(){document.querySelectorAll('.event').forEach(b=>b.classList.add('shape-event'));document.querySelectorAll('.chip').forEach(b=>b.classList.add('shape-nav'));document.querySelectorAll('.card').forEach(c=>c.classList.add('shape-memory'));const dock=q('cognitiveDock');dock?.querySelectorAll('button').forEach(b=>b.classList.add('shape-tool'))}
function renderTrail(){const trail=q('eventTrail'),a=active();if(!trail||!a)return;const rs=CORE.db.records.filter(r=>r.sessionId===a.sessionId&&!['session_start','session_end'].includes(r.type)).sort((x,y)=>new Date(x.timestamp)-new Date(y.timestamp)).slice(-7);trail.innerHTML=rs.length?`<div class="trailLabel">NOW · cognitive trail</div><div class="trailRow">${rs.map(r=>`<span class="trailEvent" title="${r.type}">${symbols[r.type]||'•'}</span>`).join('<span class="trailLine">—</span>')}</div>`:`<div class="trailHint">気づいた瞬間だけ記録。流れはここに育ちます。</div>`}
function addGrammarLegend(){const sec=q('visualLegend');if(!sec||q('grammarCard'))return;const card=document.createElement('div');card.id='grammarCard';card.className='card';card.innerHTML=`<div class="recordType">VISUAL GRAMMAR</div><p class="small">絵文字だけでなく、形と位置にも意味を固定します。</p><div class="grammarRows"><div><span class="flowShape flow-circle">💡</span><b> Circle</b><small> 瞬間的なEvent / 気づき</small></div><div><span class="flowShape flow-square">🧩</span><b> Square</b><small> 操作・道具・Grounding</small></div><div><span class="flowShape flow-pill">🧠</span><b> Pill</b><small> Context / Navigation / 状態</small></div><div class="grammarSpatial"><b>上</b> = 方向・現在地　 <b>中央</b> = 今起きたこと　 <b>下</b> = 支援道具・次の行動</div></div>`;sec.appendChild(card)}
function shortcut(e){if(q('session')?.classList.contains('hidden'))return;if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.metaKey||e.ctrlKey||e.altKey)return;const map={'1':'gotit','2':'question','3':'surprise','4':'distinction','5':'revisit'};if(map[e.key]){document.querySelector(`[data-event="${map[e.key]}"]`)?.click();e.preventDefault();return}const k=e.key.toLowerCase();if(k==='t')q('thoughtBtn')?.click();if(k==='c')q('workspaceBtn')?.click();if(k==='g'){q('workspaceBtn')?.click();setTimeout(()=>q('groundSituation')?.focus(),60)}if(k==='s')q('stateBtn')?.click()}
function addShortcutHint(){const session=q('session');if(!session||q('shortcutHint'))return;const d=document.createElement('div');d.id='shortcutHint';d.className='shortcutHint';d.textContent='⌨ 1💡 2❓ 3⚡ 4≠ 5↩ · T💭 C🧠 G🧩 S🌿';q('finishBtn')?.insertAdjacentElement('afterend',d)}
function pulseOnReturn(){if(!q('session')?.classList.contains('hidden'))renderTrail()}
function wire(){ensureGrammar();addGrammarLegend();addShortcutHint();document.addEventListener('keydown',shortcut);new MutationObserver(()=>{ensureGrammar();addGrammarLegend();addShortcutHint();pulseOnReturn()}).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();